### ISSUE TITLE
What is a "node"?

### ISSUE THREAD

**Issue by richardreeve** [jangevaare/PhyloTrees.jl#17]
You [agreed](https://github.com/jangevaare/PhyloTrees.jl/pull/14#issuecomment-295419104) a while ago in #14 that calling only internal nodes "nodes", and tips and roots "nonnodes" wasn't hugely helpful. I suggested calling them internal in `isinternal()`, `findnodes()` and `findnonnodes()`. This is just to remind you of that conversation if you still care.

**Comment by jangevaare** [comment]
Thank you, yes!

**Comment by richardreeve** [comment]
PS I obviously meant `findinternals()` and `findnoninternals()` (or `findexternals()`?)?!
