### ISSUE TITLE
Converting trees from other packages

### ISSUE THREAD

**Issue by dsmaynard** [jangevaare/PhyloTrees.jl#23]
Is there currently a way to convert a tree from other packages (e.g., NewickTree) so that it can be used with this this package? Otherwise I still can't find a good way to read in or actually apply this to read data.

**Comment by jangevaare** [comment]
No there's really no read/write methods provided in this package, just the basic tree construction API. PRs welcome :)

I hadn't heard of `NewickTree.jl` (thanks).

https://github.com/EcoJulia/Phylo.jl may have functionality to meet your needs.
