### ISSUE TITLE
Plot recipe for Makie?

### ISSUE THREAD

**Issue by cyanescent** [jangevaare/PhyloTrees.jl#25]
Including a plot recipe for Makie.jl would be very useful. I guess I should learn to write it to port this nice package to the Makie visualization ecosystem.

**Comment by jangevaare** [comment]
Contributions welcome! Unfortunately I haven't had much time to improve my Julia packages myself these last years. You may also check out [Phylo.jl](https://github.com/EcoJulia/Phylo.jl) which has more visualization options and active development.
