### ISSUE TITLE
@tbreloff's humble request

### ISSUE THREAD

**Issue by jangevaare** [jangevaare/PhyloTrees.jl#8]
Hey @tbreloff, I came across your humble request on RecipesBase readme. I'm using a plot recipe in my package PhyloTrees.jl. An example can be seen on line 26 of the following notebook: https://github.com/jangevaare/PhyloTrees.jl/blob/master/PhyloTreesDemo.ipynb

And the recipe itself is here:
https://github.com/jangevaare/PhyloTrees.jl/blob/master/src/plot.jl

Thanks for your work!

**Comment by tbreloff** [comment]
Awesome thanks for the note! A quick suggestion... It's nice to use the
'-->' operator for colors and other things a user may wish to override. As
you have it, you force the color with the ':=' operator.

**Comment by jangevaare** [comment]
Thanks!
